name: Add Tags to EKS Cluster

on:
  workflow_dispatch:
    inputs:
      resource_tags:
        required: true
        description: 'Metadata that assists with categorization and organization.'
        type: string
      entity_identifier:
        required: true
        description: 'Entity identifier'
        type: string
      entity_arn:
        required: true
        description: 'EKS resource ARN'
        type: string
      entity_title:
        required: true
        description: 'Entity title'
        type: string
      run_id:
        required: true
        description: 'Port run ID'
        type: string

jobs:
  tag-eks-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Inform Port of workflow start
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{ inputs.run_id }}
          logMessage: Configuring AWS credentials to add tags to EKS with domain ${{ inputs.entity_title }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.TF_USER_AWS_KEY }}
          aws-secret-access-key: ${{ secrets.TF_USER_AWS_SECRET }}
          aws-region: ${{ secrets.TF_USER_AWS_REGION }}

      - name: Add tags to EKS
        run: aws eks tag-resource --resource-arn ${{ inputs.entity_arn }} --tags ${{ inputs.resource_tags }}

      - name: Inform Port about EKS tag addition success
        if: success()
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{ inputs.run_id }}
          status: 'SUCCESS'
          logMessage: ✅ EKS resource with name ${{ inputs.entity_title }} tagged successfully
          summary: EKS tag addition completed successfully

      - name: Inform Port about EKS tag addition failure
        if: failure()
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{ inputs.run_id }}
          status: 'FAILURE'
          logMessage: ❌ Failed to add tags to EKS with name ${{ inputs.entity_title }}
          summary: EKS tag addition failed
